server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://self-healing-backend-svc:5000;
    }

    location /simulate-error {
        proxy_pass http://self-healing-backend-svc:5000;
    }

    location /health {
        proxy_pass http://self-healing-backend-svc:5000;
    }
}