apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: self-healing-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: self-healing.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: self-healing-frontend-svc
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: self-healing-backend-svc
            port:
              number: 5000